name: MLflow CI

on:
  push:
    branches: [ main ]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: pip install mlflow pandas scikit-learn

    - name: Run MLflow Project
      run: mlflow run .
